spring.application.name=JobListing
spring.datasource.url=jurl
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.security.user.name=username
spring.security.user.password=password

